target 'Floq' do
    use_frameworks!

  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'DKImagePickerController'
  pod 'Firebase/Database'
  pod 'IGListKit'
 
end

