target 'Floq' do
    use_frameworks!

  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'FBSDKCoreKit', '4.36.0'
  pod 'FBSDKLoginKit', '4.36.0'
  pod 'FacebookCore', '0.4'
  pod 'FacebookLogin', '0.4'
  pod 'DKImagePickerController'
  pod 'Firebase/Database'
  pod 'IGListKit'
 
end

